name: "HerraduraRP"
lang: "en"
token: "TokenAquii" # Discord bot token
interval: 10000 # ms
server: "132.74.217.48:30120"

message:
  enabled: true
  channel: "1121127664221163530" # Channel id
status:
  enabled: true
